### PR TITLE
ENH: Enable loading of pymatgen CompleteDos objects

### PR DESCRIPTION
**Pull request by utf**
We are toying with the idea of adding galore weighted projected density of states to the Materials Project frontend. As all the MP dos data is stored as CompleteDos objects I've added the option of processing these objects rather than vasprun files.

### CODE REVIEW

**Comment by utf** [comment]
Hmm, tests are failing on Python 2. This is due to one of pymatgen's dependencies (monty) which I'm using for very convenient serialisation.

As pymatgen is dropping support for Python 3 at the end of this year, maybe I could add a Python 3 requirement for the pymatgen tests. What do you think?

**Comment by ajjackson** [comment]
I have no objection to dropping python2 support entirely

**Comment by utf** [comment]
Ok, I've removed Python 2.7 support. Please merge if you're happy with the changes.

**Comment by ajjackson** [comment]
This looks great. The next version number update should be a substantial bump to reflect the Python 2 drop. Are there any related major changes we should make before then?

**Comment by ajjackson** [comment]
I have pushed some further python2 purges to master. Hopefully it didn't break anything...

**Pull request merged**
