### PR TITLE
Migrate from Travis CI to Github actions

### PR DESCRIPTION
**Pull request by ajjackson**
Travis is confusing/limited after their update/migration. Let's move Galore's continuous integration to Github actions.

This is needed to progress #35 as currently the tests are not running.

We need to drop Python 3.4 support if using this platform, because the testing setup only provides for Python 3.5+. We can't support Python 3.4 if we aren't testing it.

There is room for improvement; I would like to also test that Galore works without Pymatgen, and maybe only check GPAW under some circumstances (e.g. push or master and/or PR with "gpaw" in the name). A "release" action would be nice too. But for now this is holding up work and we need to get things moving again. Enhancements can come later.

### CODE REVIEW

**Comment by utf** [comment]
Looks good to me. Any harm in also testing python 3.8?

**Comment by ajjackson** [comment]
> Looks good to me. Any harm in also testing python 3.8?

I'll give it a try!

**Comment by ajjackson** [comment]
Seems to work :sweat_smile:

**Comment by utf** [comment]
Great! Looks good to merge.

**Pull request merged**
